using System;
using System.Globalization;
using System.Collections.Generic;

namespace rankings2.Services
{
    public static class NameFixer
    {
        public static string FirstCharToUpper(string value)
        {
            char[] array = value.ToCharArray();
            // Handle the first letter in the string.  
            if (array.Length >= 1)
            {
                if (char.IsLower(array[0]))
                {
                    array[0] = char.ToUpper(array[0]);
                }
            }
            // Scan through the letters, checking for spaces.  
            // ... Uppercase the lowercase letters following spaces.  
            for (int i = 1; i < array.Length; i++)
            {
                if (array[i - 1] == ' ')
                {
                    if (char.IsLower(array[i]))
                    {
                        array[i] = char.ToUpper(array[i]);
                    }
                }
            }
            return new string(array);
        }

        public static Dictionary<string, string> americans = new Dictionary<string, string>()
        {
            {"Jordan Ernest Burroughs", "Jordan Burroughs"},
            {"Jordan Michael Oliver", "Jordan Oliver"},
            {"Daton Duain Fix", "Daton Fix"},
            {"Tyler Lee Graff", "Tyler Graff"},
            {"James Malcolm Green", "James Green"},
            {"Klye Douglas Dake", "Kyle Dake"},
            {"Nicholas Edward Gwiazdowski", "Nick Gwiazdowski"},
            {"Anthony Robert Nelson", "Tony Nelson"},
            {"Michael Joseph Kosoy", "Mike Kosoy"},
            {"Nicholas Gwiazdowski", "Nick Gwiazdowski"},
            {"Zachery William Rey", " Zach Rey"},
            {"Gable Dan Steveson", "Gable Steveson"},
            {"Mason Mark Parris", "Mason Parris"},
            {"Youssif Ibrahim Hemida", "Youssif Hemida"},
            {"Daniel Gregor Clifton Kerkvliet Jr", "Daniel Kerkvliet"},
            {"Thomas Patrick Gilman", "Thomas Gilman"},
            {"Joseph Daniel Colon", "Joe Colon"},
            {"Stevan Andria Micic", " Stevan Micic"},
            {"Darian Toi Cruz", "Darian Cruz"},
            {"Frank Vincent Perrelli Iv", "Frank Perrelli"},
            {"Jack Michael Mueller", "Jack Mueller"},
            {"Nicholas Megaludis", "Nico Megaludis"},
            {"Anthony Joseph Ramos", "Tony Ramos"},
            {"Cory John Clark", "Cory Clark"},
            {"Sean Christian Fausz", "Sean Fausz"},
            {"Gabriel Robert Tagg", "Gabe Tagg"},
            {"Joshua Pavel Saunders", "Josh Saunders"},
            {"Alec Christopher Hoover", "Alec Hoover"},
            {"Jonathan R Morrison ", "Jon Morrison"},
            {"Charles Goldsberry Tucker", "Chaz Tucker"},
            {"Zain Allen Retherford", "Zain Retherford"},
            {"Joseph Christopher Mc Kenna", "Joey McKenna"},
            {"Joseph Christopher McKenna", "Joey McKenna"},
            {"Bernard Walter Futrell", "BJ Futrell"},
            {"Evan Richard Henderson", "Evan Henderson"},
            {"John Michael Diakomihalis", "Yianni Diakomihalis"},
            {"Domonick Petro Demas", "Dom Demas"},
            {"Logan Jeffery Stieber", "Logan Stieber"},
            {"Jayson Douglas Ness", "Jayson Ness"},
            {"Joshua Michael Kindig", "Josh Kindig"},
            {"Andrew James Hoover", "Andrew Hoover"},
            {"Brandon Everett Callow", "Brandon Callow"},
            {"Spencer John Dusi", "Spencer Dusi"},
            {"John Andrew Simmons", "Andy Simmons"},
            {"Jaydin Selsor Eierman", "Jaydin Eierman"},
            {"Yahya Abdullah Thomas", "Yahya Thomas"},
            {"Colton James McCrystal", "Colton McCrystal"},
            {"Dean Jacob Heil", "Dean Heil"},
            {"Anthony James Ashnault", "Anthony Ashnault"},
            {"Jason Lyle Chamberlain", "Jason Chamberlain"},
            {"Frank Aniello Molinaro", "Frank Molinaro"},
            {"Austin Alexander Victor", "Austin Victor"},
            {"Brandon Alexander Barton", "Brandon Barton"},
            {"Jarrad Keith Lasko", "Jarrad Lasko"},
            {"Brady Gary Berge", "Brady Berge"},
            {"Brayton Edward Lee", "Brayton Lee"},
            {"Hayden Michael Hidlay", "Hayden Hidlay"},
            {"Alec William Pantaleo", "Alec Pantaleo"},
            {"Brandon John Sorenson", "Brandon Sorenson"},
            {"Logan Wesley Massa", "Logan Massa"},
            {"Isaiah Alexander Martinez", "Isaiah Martinez"},
            {"Alexander Landon Smythe", "Alex Smythe"},
            {"David Aaron Carr", "David Carr"},
            {"Mekhi Kevin Lewis", "Mekhi Lewis"},
            {"Jason Michael Nolf", "Jason Nolf"},
            {"Alexander David Dieringer", "Alex Dieringer"},
            {"Muhamed Mustafa Mc Bryde", "Muhamed McBryde"},
            {"Muhamed Mustafa McBryde", "Muhamed McBryde"},
            {"David Vincent Mc Fadden", "David McFadden "},
            {"David Vincent McFadden", "David McFadden"},
            {"Aaron Marquel Brooks", "Aaron Brooks"},
            {"Daniel Joseph Novak", "Daniel Novak"},
            {"Seth Matthew Winkle", "Seth Winkle"},
            {"Kyle Dylan Roberts", "Kyle Roberts"},
            {"David Morris Taylor", "David Taylor"},
            {"Mark John Hall Ii", "Mark Hall"},
            {"Mark John Hall", "Mark Hall"},
            {"James Patrick Downey", "Pat Downey"},
            {"James Patrick Downey Iii", "Pat Downey"},
            {"Samuel Joseph Brooks", "Sammy Brooks"},
            {"Nicholas Joseph Heflin", "Nick Heflin"},
            {"Trent Niemond Hidlay", "Trent Hidlay"},
            {"Lou John Perez", "Lou Perez"},
            {"Christian Brian Hipsher", "Christian Hipsher"},
            {"Matthew Christopher Ferraro", "Matthew Ferraro"},
            {"Kenneth Rashad Courts", "Kenny Courts"},
            {"J’den Michael Tbory Cox", "J’den Cox"},
            {"Michael Justin Macchiavello", "Mike Macchiavello"},
            {"Bo Dean Nickal", "Bo Nickal"},
            {"Lucas John Davison", "Lucas Davison"},
            {"Christian William Brunner", "Christian Brunner"},
            {"Jacob Alexander Warner", "Jacob Warner"},
            {"Kyle Frederick Snyder", "Kyle Snyder"},
            {"Benjamin Errol Provisor", "Ben Provisor"},
            {"Ty Ryan Jack Walz", "Ty Walz"},
            {"Hayden Nicholas Zillmer", "Hayden Zillmer"},
            {"Kyven Ross Gadson", "Kyven Gadson"},
            {"Kollin Raymond Moore", "Kollin Moore"},
            {"Zachery Samuel Elam ", "Zach Elam"},
            {"Nathan Joseph Burak", "Nathan Burak"},
            {"Micah Leo Burak", "Micah Burak"},
            {"Franklin Gomez Matos", "Franklin Gomez"},
            {"Frank Chamizo Marquez", "Frank Chamizo"},
            {"Jeandry Garzon Caballero", "Geandry Garzon"},
            {"Jeandry Garzon", "Geandry Garzon"},
            {"Geandry Garzon Caballero", "Geandry Garzon"},
            {"Alejandro Enrique Valdes Tobier", "Alejandro Valdes"},
            {"Alejandro Valdes Tobier", "Alejandro Valdes"},
            {"Bajrang Bajrang", "Bajrang Punia"},
            {"Reineri Andreu Ortega", "Reineri Andreu"},
            {"Reineris Salas Perez", "Reineris Salas"},
            {"Alan Lavrentevitch Khugaev", "Alan Khugaev"},
            {"Bililal Makhov", "Bilyal Makhov"},
            {"Oleksandr Khotsianivskyi", "Alexander Khotsianivski"},
            {"Anzor Ruslanovitch Khizriev", "Anzor Khizriev"},
            {"Said Gamidovitch Gamidov", "Said Gamidov"},
            {"Yudenny Alpajon Estevez", "Yudenny Alpajon"},
            {"Alexander Bogomoev", "Aleksander Bogomoev"},
            {"Aleksandr Bogomoev", "Aleksander Bogomoev"},
            {"Nachyn Sergeevitch Kuular", "Nachyn Kuular"},
            {"Haji Aliyev", "Haji Aliev"},
            {"Zavur Uguev", "Zaur Uguev"},
            {"Nurislam (artas) Sanayev (sanaa)", "Nurislam Sanayev"},
            {"Ismail Hajiyev", "Ismail Hajiev"},
            {"Khalid Iakhiev", "Khalid Yakhiev"},
            {"Ertine Mortuy Ool", "Ertine Mortuy-Ool"},
            {"Ertine Mortuy-ool", "Ertine Mortuy-Oo"},
            {"Ilias Bekbulatov", "Ilyas Bekbulatov"},
            {"Bekkhan Goigereev", "Bekhan Goigereev"},
            {"Eduard Grigoriev", "Eduard Grigorev"},
            {"Ismail Muskaev", "Ismail Musukaev"},
            {"Iszmail Muszukajev", "Ismail Musukaev "},
            {"Tulga Tumur Ochir", "Tulga Tumur-Ochir"},
            {"Tulga Tumur-ochir", "Tulga Tumur-Ochir"},
            {"Peiman Bioukagha Biabani", "Pejman Biabani"},
            {"Peiman Biabani", "Pejman Biabani"},
            {"Peyman Biabani", "Pejman Biabani"},
            {"Hassan Aliazam Yazdanicharati", "Hassan Yazdani"},
            {"Amir Maghsoudi", "Amir Magsoudi"},
            {"Amirmohammad Babak Yazdanicherati", "Amir Yazdani"},
            {"Domenic Michael Abou Nader", "Domenic Abounader"},
            {"Domenic Michael Abounader", "Domenic Abounader"},
            {"Myles Nazem Amine", "Myles Amine"},
            {"Jaime Yusept Espinal", "Jaime Espinal"},
            {"Uladislau Andreyeu", "Vladislav Andreev"},
            {"Kumar Ravi", "Ravi Kumar"},
            {"Reza Ahmadali Atrinagharchi", "Reza Atri"},
            {"Hamed Zarrin", "Hamid Zarrin"},
            {"Hamid Zarrin Peydar", "Hamidreza Zarrin"},
            {"Hamidreza Zarrin Peykar", "Hamidreza Zarrin"},
            {"Abbas Fourotan", "Abbas Foroutanrami"},
            {"Arshak Mohebbi", "Arashk Mohebbi"},
            {"Yadollah Mohammadkazem Mohebi", "Yadollah Mohebbi"},
            {"Yadollah Mohebi", "Yadollah Mohebbi"},
            {"Ali Khalil Shabanibengar", "Ali Shabani"},
            {"Sajad Gholamhossein Azizi", "Sajad Azizi"},
            {"Mojtaba Mohammadshafie Goleij", "Mojtaba Goleij"},
            {"Alireza Mohammad Karimimachiani", "Alireza Karimi"},
            {"Ali Reza Abbasali Abdollahi", " Ali Reza Abdollahi"},
            {"Hossein Lotfali Shahbazigazvar", "Hossein Shahbazi"},
            {"Seyedabolfazl Seyedabbasali Hashemijouybari", "Seyed Hashemi"},
            {"Kamran Ghasempour", "Kamran Ghasempour"},
            {"Ezzatollah Abbas Akbarizarinkolaei ", "Ezzatollah Akbari"},
            {"Sajjad Saberali Gholami", "Sajjad Gholami "},
            {"Reza Alireza Afzalipaemami", "Reza Afzali"},
            {"Ali Bakhtiar Savadkouhi", "Ali Savadkouhi"},
            {"Navid Morad Zanganeh", "Navid Zanganeh"},
            {"Mostafa Mohabbali Hosseinkhani", "Mostafa Hosseinkhani "},
            {"Mohammad Ashghar Nokhodilarimi", "Mohammad Nokhodi"},
            {"Yones Aliakbar Emamichoghaei", "Yones Emami"},
            {"Amirhossein Morteza Gholi Kavousi", "Amirhossein Kavousi"},
            {"Mohmmadsadegh Biglar Firouzpourbandpei", "Mohmmad Firouzpour"},
            {"Amirhossein Ali Hosseini", "Amirhossein Hosseini"},
            {"Amirhossein Azim Maghsoudi", "Amir Magsoudi"},
            {"Morteza Hassanali Ghiasi Cheka", "Morteza Ghiasi "},
            {"Behnam Eshagh Ehsanpoor", "Behnam Ehsanpoor"},
            {"Mohammadbagher Esmaeil Yakhkeshi", "Mohammad Yakhkeshi"},
            {"Iman Mokhtar Sadeghikoukandeh", "Iman Sadeghi"},
            {"Amir Aliakbar Parasteh", "Amir Parasteh"},
            {"Alireza Nosratolah Sarlak", "Alireza Sarlak"},
            {"Parviz Khodavirdi Hadibasmanj", "Parviz Hadi"},
            {"Amir Hossein Abbas Zare", "Amir Zare"},
            {"Amin Hossein Taheri", "Amin Taheri"},
            {"Igor Alekseevitch Ovsiannikov", "Igor Ovsiannikov"},
            {"Shamil Alievitch Musaev", "Shamil Musaev"},
            {"Zbigniew Mateusz Baranowski", "Zbigniew Baranowski"},
            {"Alexander Robert Moore", "Alexander Moore"},
            {"Akhmed Shiabdinovitch Gadzhimagomedov", "Akhmed Gadzhimagomedov"},
            {"Khaled Omr Zaki Mohamed Abdalla", "Khaled Abdalla"},
            {"Luis Felipe Vivenes Urbaneja", "Luis Urbaneja"},
            {"Jose Cuba Vazquez", "Jose Vazquez"},
            {"Jere Tapani Heino", "Jere Heino"},
            {"Amarveer Dhesi", "Amar Dhesi"},
            {"Catriel Pehuen Muriel", "Catriel Muriel"},
            {"Florian Skilang Temengil", "Florian Temengil"},
            {"Aly Medhat Abde Barghout", "Aly Barghout"},
            {"Jackson Jerome Serna", "Jackson Serna"},
            {"Kamil Tomasz Kosciolek", "Kamil Kosciolek"},
            {"Bradley Thomas Hildenbrandt", "Bradley Hildenbrandt"},
            {"Huseyin Mehmet Civelek", "Huseyin Mehmet Civelek"},
            {"Oscar Eduardo Tigreros Urbano", "Oscar Tigreros"},
            {"Horst Justin Junior Lehr", "Horst Lehr"},
            {"Levan Metreveli Vartanov", "Levan Metreveli"},
            {"Mikyay Salim Naim", "Salim Naim Mikyay"},
            {"Vijay Bajirao Patil", "Vijay Patil"},
            {"Robert Tyson T Likiaksa", "Robert Likiaksa"},
            {"Razvan Marian Kovacs", "Razvan Kovacs"},
            {"Richard Gabriel Townsell", "Gabe Townsell"},
            {"Andrei Bekreneu", "Andrey Bekrenev"},
            {"Sonba Tanaji Gongane", "Sonba Gongane"},
            {"Yowlys Bonne", "Yowlys Bonne Rodriguez"},
            {"Vladimir Vladimirov Dubov", "Vladimir Dubov"},
            {"Frederik Cornelius Johannes Nortje", "Frederik Nortje"},
            {"Suraj Rajkumar Kokate", "Suraj Kokate"},
            {"Mahdi Saeed Shirazi", "Mahdi Shirazi"},
            {"Malik Michael Amine", "Malik Amine"},
            {"Amr Reda Ramadan Hussen", "Amr Reda"},
            {"Ethan Mikquin Tomapa Aguigui", "Ethan Aguigui"},
            {"Mihail Iliev Georgiev", "Mihail Georgiev"},
            {"Haji Mohamad Ali", "Haji Ali"},
            {"Yoandrys Grant Collazo", "Yoandrys Collazo"},
            {"Michael Stanley David Asselstine", "Michael Asselstine"},
            {"Jafar Shams Nateri", "Jafar Shamsnateri"},
            {"Nader Haj Aghania", "Nader Hajaghania"},
            {"Morteza Ghiyasi", "Morteza Ghiasi"},
            {"Mohammad Firouzpoor", "Mohammad Firouzpour"},
            {"Geandry Garzón Caballero", "Geandry Garzon"},
            {"Zeravan Tareq Saeed Saeed", "Zeravan Saeed"},
            {"Jorge Ivan Llano", "Jorge Llano"},
            {"Anthony Jose Montero Chirinos", "Anthony Montero"},
            {"Aly Ibrahim Abdelhamid Abdelhamid", "Aly Abdelhamid"},
            {"Colton James Mccrystal", "Colton Mccrystal"},
            {"Niklas Dietmar Dorn", "Niklas Dorn"},
            {"Dillon Emmanuel Williams", "Dillon Williams"},
            {"Ahmet Salim Yigit", "Ahmet Yigit"},
            {"Nikola Delchev Levenov", "Nikola Levenov"},
            {"Connor Quinn Mcneice", "Connor McNeice"},
            {"Patryk Krzysztof Olenczyn", "Patryk Olenczyn"},
            {"Joshua Miguel Trambulo Riley", "Joshua Riley"},
            {"Younes Emami", "Yones Emami"},
            {"Omer Faruk Cayir", "Omer Cayir"},
            {"Mateusz Dariusz Kampik", "Mateusz Kampik"},
            {"Nima Hossein Eshfaghiamiri", "Nima Eshfaghiamiri"},
            {"Franklin Maren Castillo", "Franklin Maren"},
            {"Haislan Antonio Veranes Garcia", "Haislan Garcia "},
            {"Veselin Georgiev Petrov", "Veselin Petrov"},
            {"Georgi Valentinov Vangelov", "Georgi Vangelov"},
            {"Samy Hamdy Amin", "Samy Moustafa"},
            {"Jasmit Singh Phulka", "Jasmit Phulka"},
            {"Victor Eduardo Hernandez Luna", "Victor Hernandez"},
            {"Nestor Joaquin Tafur Barrios", "Nestor Tafur"},
            {"Miroslav Stefanov Kirov", "Miroslav Kirov"},
            {"Johann Christoph Steinforth", "Johann Steinforth"},
            {"Bat Erdene Byambasuren", "Bat-Erdene Byambasuren"},
            {"Jakub Patryk Wladczyk", "Jakub Wladczyk"},
            {"Saifeldin Shokry Mohamed Mahmoud Elkoumy", "Saifeldin Elkoumy"},
            {"Matthew Trevor Bartlett", "Matthew Bartlett"},
            {"Pawel Tomasz Malicki", "Pawel Malicki"},
            {"Ramazan Ishak Sari", "Ramazan Sari"},
            {"Mostafa Mahmoud Mohamed Sayed", "Mostafa Sayed"},
            {"Marcin Piotr Majka", "Marcin Majka"},
            {"Oktay Ruzhdi Hasan", "Oktay Hasan"},
            {"Samuel Jacob Barmish", "Samuel Barmish"},
            {"Kyle Douglas Dake", "Kyle Dake"},
            {"Muhammet Nuri Kotanoglu", "Muhammet Kotanoglu"},
            {"Bahman Mohammad Teymouri", "Bahman Teymouri"},
            {"Omer Faruk Karadeniz", "Omer Karadeniz"},
            {"Uladzislau Yeliseyeu", "Vladislav Yeliseev"},
            {"Engin Rashid Ismail", "Engin Ismail"},
            {"Mojtaba Yousefali Asghari Osmavandani", "Mojtaba Osmavandani"},
            {"Ezzatollah Abbas Akbarizarinkolaei", "Ezzatollah Akbari"},
            {"Akbari Ezzatollah", "Ezzatollah Akbari"},
            {"Ethan Adrian Ramos", "Ethan Ramos"},
            {"Carlos Arturo Izquierdo Mendez", "Carlos Mendez"},
            {"Krzysztof Grzegorz Sadowik", "Krzysztof Sadowik"},
            {"Chasen James Blair", "Chasen Blair"},
            {"Alexander Moore", "Alexander Robert Moore"},
            {"Kamran Ghorban Ghasempour", "Kamran Ghasempour"},
            {"Johannes Martin Deml", "Johannes Deml"},
            {"Yurieski Torreblanca Queralta", "Yurieski Torreblanca"},
            {"Ahmed Ruslanovic Dudarov", "Ahmed Dudarov"},
            {"Taimuraz Friev Naskidaeva", "Taimuraz Friev"},
            {"Pool Edinson Ambrocio Greifo", "Pool Greifo"},
            {"Sajjad Saeid Habibiehsani", "Sajjad Habibiehsani"},
            {"Hunter Jeffery Lee", "Hunter Lee"},
            {"Pedro Francisco Ceballos Fuentes", "Pedro Ceballos Fuentes"},
            {"Shai Shabtai Shotashvili", "Shai Shotashvili"},
            {"Michal Jan Bielawski", "Michal Bielawski"},
            {"Myles Najee Martin", "Myles Martin"},
            {"Mihai Nicolae Palaghia", "Mihai Palaghia"},
            {"Ivan Kostadinov Stefanov", "Ivan Stefanov"},
            {"Yonger Pauli Bastida Pomares", "Yonger Bastida"},
            {"Batyrbek Tcakulov", "Batyrbek Tsakulov"},
            {"Bozhidar Mateev Todorov", "Bozhidar Todorov"},
            {"J'den Michael Tbory Cox", "J’den Cox"},
            {"Machiel Johannes Grobler", "Machiel Grobler"},
            {"Chase Keith Singletary", "Chase Singletary"},
            {"Nishan Preet Singh Randhawa", "Nishan Randhawa"},
            {"Magomedgadji Omardibirovich Nurov", "Magomedgadji Nurov"},
            {"Magomed Idrisovitch Ibragimov", "Magomed Ibragimov"},
            {"Tanner Ryan Sloan", "Tanner Sloan"},
            {"Ikjyot Singh Randhawa", "Ikjyot Randhawa"},
            {"Erik Sven Thiele", "Erik Thiele"},
            {"Yunus Emre Dede", "Yunus Dede"},
            {"Dzianis Khramiankou", "Dzianis Khramiankov"},
            {"Pavlo Oliinyk", "Pavlo Olejnyik"},
            {"Ricardo Adrian Baez", "Ricardo Baez"},
            {"Zachery Samuel Elam", "Zach Elam"},
            {"Richard Phillip Junior Deschatelets", "Richard Deschatelets"},
            {"Charles Zachary Merrill", "Charles Merrill"},
            {"Aliaksandr Hushtyn", "Aleksandr Hushtyn"},
            {"Ryan John Malo", "Ryan Malo"},
            {"Rares Daniel Chintoan", "Rares Chintoan"},
            {"Dzimchyk Rynchynau", "Dimchik Rinchinov"},
            {"Mahir Amiraslanov", "Makhir Amiraslanov"},
            {"Randy Adrian Vock", "Randy Vock"},
            {"Viktor Viktorowitsch Lyzen", "Viktor Lyzen"},
            {"Marwane Ahmed Yezza", "Marwane Yezza"},
            {"Niurgun Skriabin", "Nyurgun Skryabin"},
            {"Hor Ohannesian", "Gor Oganesyan"},
            {"George Anthony Ramm", "George Ramm"},
            {"Nyurugin Skriabin", "Nyurgun Skryabin"},
            {"Niurhun Skrabin", "Nyurgun Skryabin"},
            {"Kevin Christopher Henkel", "Kevin Henkel"},
            {"Filip Stefanov Novachkov", "Filip Novachkov"},
            {"Ali Pasha Ruslanovich Umarpashaev", "Ali Pasha Umarpashaev"},
            {"Magomedrasul Muhtarovitch Gazimagomedov", "Magomedrasul Gazimagomedov"},
            {"Azamat Nurykau", "Azamat Nurikau"},
            {"Murtazali Raxmatullayevic Muslimov", "Murtazali Muslimov"},
            {"Johnny Just Bur", "Johnny Bur"},
            {"Jonatan Alvarez Diaz", "Jonathan Alvarez"},
            {"Vasile Madalin Minzala", "Vasile Minzala"},
            {"Zsombor Istvan Gulyas", "Zsombor Gulyas"},
            {"Magomed Eldarovitch Ramazanov", "Magomed Ramazanov"},
            {"Mahamedkhabib Kadzimahamedau", "Mahamedkhabib Kadimagomedov"},
            {"Franco Mario Buettner", "Franco Buettner"},
            {"Dan Or Tsesarsky", "Dan Tsesarsky"},
            {"Akhmed Adamovitch Magamaev", "Ahmed Magamaev"},
            {"Akhmed Magamaev", "Ahmed Magamaev"},
            {"Svetoslav Zhivkov Dimitrov", "Svetoslav Dimitrov"},
            {"Richard Ferenc Ligeti", "Richard Ligeti"},
            {"Ville Tapani Heino", "Ville Heino"},
            {"Magomed Guseynovitch Kurbanov", "Magomed Kurbanov"},
            {"Nurmagomed Gadzhiyev", "Nurmagomed Gadzhiev"},
            {"Nikolay Simeonov Chterev", "Nikolay Chterev"},
            {"Vladislav Baitcaev", "Vladislav Baitsaev"},
            {"Tahar Lutfi Shihab Al Zubaidi", "Tahar Al Zubaidi"},
            {"Pin Cheong Lonard Arthur Kong", "Pin Kong"},
            {"Parviz Hadibasmanj", "Parviz Hadi"},
            {"Ahmed Salah Majeed Al Jamie", "Ahmed Al Jamie"},
            {"Gamal Mohammed Yahya Alsabri", "Gamal Alsabri"},
            {"Ahmed Jawad Kadhim Al Zaidawi", "Ahmed Al Zaidawi"},
            {"Muhammad Firdhaus Ming Ming Ng", "Muhammad Ming Ng"},
            {"Kum Song Kang", "Kumsong Kang"},
            {"Rami Ismail M Alama", "Rami Alama"},
            {"Eddy Zulqarnain Khidzer", "Eddy Khidzer "},
            {"Uladzislau Andreyeu", "Vladislav Andreev"},
            {"Rahul Balasaheb Aware", "Rahul Aware"},
            {"Mohammed Al Jawad Zuhair K Kareem", "Mohammed Kareem"},
            {"Divoshan Charles Fernando", "Divoshan Fernando "},
            {"Mehran Nasiriafrachali", "Mehran Nasiri"},
            {"Karam Shakir Mhmood Mahmood", "Karam Mahmood "},
            {"Mohammed J M Th A Abdulkareem", "Mohammed Abdulkareem"},
            {"Abdullrahman Ibrahim A. Ibrahim", "Abdullrahman Ibrahim"},
            {"Bat-erdene Byambasuren", "Bat-Erdene Byambasuren"},
            {"Byambadorj Bat Erdene", "Bat-Erdene Byambadorj"},
            {"Khash-erdene Byambadorj", "Khash-Erdene Byambadorj"},
            {"Byambadorj Bat-erdene", "Bat-Erdene Byambadorj"},
            {"Byambasuren Bat Erdene", "Bat-Erdene Byambasuren"},
            {"Amit Kumar Dhankhar", "Amit Dhankhar"},
            {"Mhd Feda Aldin Al Asta", "Mohammed Al Asta"},
            {"Ahmad Yousef Bazrighaleh", "Ahmad Bazri"},
            {"Issa Abdulsalam Abdulwahhab Al Obaidi", "Issa Al Obaidi"},
            {"Jitender Jitender", "Jitender"},
            {"Vicky Vicky", "Vicky"},
            {"Satywart Kadian", "Satyawart Kadian"}


        };



        public static string FixAmerican(string newAmericanName)

        {


              foreach (var pair in americans)
                {
                string name = pair.Key;

                if (newAmericanName.Contains(name))
                {
                    return pair.Value;
                }
               
                }

            return newAmericanName;



        }
    }
}
